# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(788, 772)
        self.jam = QtWidgets.QTextBrowser(Dialog)
        self.jam.setGeometry(QtCore.QRect(150, 160, 151, 101))
        self.jam.setObjectName("jam")
        self.menit = QtWidgets.QTextBrowser(Dialog)
        self.menit.setGeometry(QtCore.QRect(310, 160, 151, 101))
        self.menit.setObjectName("menit")
        self.detik = QtWidgets.QTextBrowser(Dialog)
        self.detik.setGeometry(QtCore.QRect(470, 160, 151, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.detik.setFont(font)
        self.detik.setObjectName("detik")
        self.Lap = QtWidgets.QPushButton(Dialog)
        self.Lap.setGeometry(QtCore.QRect(540, 330, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Lap.setFont(font)
        self.Lap.setObjectName("Lap")
        self.Mulaistop = QtWidgets.QPushButton(Dialog)
        self.Mulaistop.setGeometry(QtCore.QRect(310, 330, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Mulaistop.setFont(font)
        self.Mulaistop.setObjectName("Mulaistop")
        self.LayarLap = QtWidgets.QTextBrowser(Dialog)
        self.LayarLap.setGeometry(QtCore.QRect(80, 430, 601, 291))
        self.LayarLap.setObjectName("LayarLap")
        self.keluar = QtWidgets.QPushButton(Dialog)
        self.keluar.setGeometry(QtCore.QRect(80, 330, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.keluar.setFont(font)
        self.keluar.setObjectName("keluar")

        self.retranslateUi(Dialog)
        self.keluar.clicked.connect(Dialog.exec) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Lap.setText(_translate("Dialog", "Lap"))
        self.Mulaistop.setText(_translate("Dialog", "Mulai/Stop"))
        self.keluar.setText(_translate("Dialog", "Keluar"))
